version: 2.1

orbs:
  node: circleci/node@5.0.1

jobs:
  deploy:
    executor:
      name: node/default
      tag: &node-ver '16.10'
    steps:
      - checkout
      - run: npx semantic-release

workflows:
  test_and_deploy:
    jobs:
      - node/test:
          version: *node-ver
          run-command: ci:test
      - deploy:
          requires:
            - node/test
          filters:
            branches:
              only:
                - master
